### ISSUE TITLE
Checkpoint?

### ISSUE THREAD

**Issue by rohansachdeva** [igem-toronto/plasmidai#7]
Hi iGEM Toronto Team,
Really impressive work on building a generative model for plasmid sequences! We want to try out your model and noticed that while there is a training script, the checkpoint file is not provided. Do you mind sharing this?

Thanks!

**Comment by Adibvafa** [comment]
@rohansachdeva Thank you for your kind words! Unfortunately, we are not releasing the checkpoint after we have approvals from Garton Lab, possibly after iGEM Jamboree.
